---
- name: Apache - Install apache server
  apt:
    name: apache2
  tags:
    - apache

- name: Apache - Install mod_wsgi
  apt:
    name: libapache2-mod-wsgi-py3
  tags:
    - apache

- name: Apache - Self Signed Cert
  notify:
    - Restart Apache2
  # We do not want to default to a self signed cert in production on partial configuration.
  when: cloud_snitch_web_ssl_cert is not defined and cloud_snitch_web_ssl_key is not defined
  tags:
    - apache
    - config
  args:
    creates: "{{ cloud_snitch_web_ssl_cert_file }}"
  command: >
    openssl req -new -nodes -sha256 -x509
    -subj "{{ cloud_snitch_web_self_signed_subject }}"
    -days 3650
    -keyout "{{ cloud_snitch_web_ssl_key_file }}"
    -out "{{ cloud_snitch_web_ssl_cert_file }}"

- name: Apache - SSL Key
  notify:
    - Restart Apache2
  when: cloud_snitch_web_ssl_key is defined
  template:
    src: ssl_key.j2
    dest: "{{ cloud_snitch_web_ssl_key_file }}"
  tags:
    - config
    - apache

- name: Apache - SSL Cert
  notify:
    - Restart Apache2
  when: cloud_snitch_web_ssl_cert is defined
  template:
    src: ssl_cert.j2
    dest: "{{ cloud_snitch_web_ssl_cert_file }}"
  tags:
    - config
    - apache

- name: Apache - modules
  apache2_module:
    name: "{{ item }}"
    state: present
  tags:
    - config
    - apache
  notify:
    - Restart Apache2
  with_items:
    - wsgi
    - rewrite
    - ssl

- name: Apache - Listen Ports
  template:
    src: listen_ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify:
    - Restart Apache2
  tags:
    - config
    - apache

- name: Apache - Cloud Snitch Web conf
  template:
    src: 090-cloudsnitch.conf.j2
    dest: /etc/apache2/sites-available/090-cloudsnitch.conf
  tags:
    - config
    - apache
  notify: Restart Apache2

- name: Apache - Disable default site
  file:
    name: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  tags:
    - apache
    - config
  notify: Restart Apache2

- name: Apache - Enable cloud_snitch_web site
  file:
    name: /etc/apache2/sites-enabled/090-cloudsnitch.conf
    state: link
    src: /etc/apache2/sites-available/090-cloudsnitch.conf
  tags:
    - config
    - apache
  notify: Restart Apache2
